services:
  api:
    build: .
    container_name: docx-parser-api
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped 